export const BATCH_PAGE_SIZE = 10;
export const BATCH_CONCURRENCY = 2; // Process 2 URLs at a time
export const FREE_BATCH_LIMIT = 10;
export const TEAM_BATCH_LIMIT = 50;
export const BATCH_ENABLE_TELEMETRY_LOG = false;
export const BATCH_DELAY_BETWEEN_GROUPS = 500; // low default pacing; adaptive cooldown handles unstable windows
export const RETRY_ATTEMPTS = 2; // Retry failed requests
export const ANALYZE_RETRY_ATTEMPTS = 4;
export const ANALYZE_RETRY_ATTEMPTS_LARGE_BATCH = 4;
export const LARGE_BATCH_THRESHOLD = 30;
export const RETRY_BASE_DELAY_MS = 1200;
export const RETRY_JITTER_MS = 300;
export const ANALYZE_RETRY_BASE_DELAY_MS = 1800;
export const MAX_BACKOFF_MS = 5000;
export const ANALYZE_FAILURE_COOLDOWN_MS = 2500;
export const ANALYZE_MIN_INTERVAL_MS = 1250;
export const ANALYZE_ADAPTIVE_COOLDOWN_BASE_MS = 2500;
export const ANALYZE_ADAPTIVE_COOLDOWN_MAX_MS = 12000;
export const ANALYZE_ADAPTIVE_COOLDOWN_STEP_DOWN_MS = 400;
