export const state = {
  lastContentHash: null,
  lastAnalysis: null,
  lastExtractedMeta: null,
  lastAnalyzedDomain: null,
  forceRefresh: false,
  currentView: "analysis",
  selectionMode: false,
  lastSelectedIndex: null,
  selectedSavedIds: new Set(),
  isRangeSelecting: false,
  isFinalizingDeletes: false,
  isUndoToastActive: false,
  pendingDeleteMap: new Map(),
  undoTimer: null,
  totalFilteredCount: 0,
  currentPage: 1,
  currentPlan: "free",
  remainingToday: null,
  usedToday: null,
  maxSavedLimit: 5,
  totalSavedCount: 0,
  dailyLimitFromAPI: 5,
  isUserInteracting: false,
  dropdownOpenedAt: 0,
  isAnalysisLoading: false,
  lastQuotaFetch: 0,
  lastAutoAnalyzeAt: 0,
  activeFilters: {
    minScore: 0,
    maxScore: 100,
    persona: "",
    searchQuery: "",
    sort: "created_at_desc"
  }
};
